#!/bin/bash -l
# Standard output and error:
#SBATCH -o ${dir_std}/ptr.out.%j 
#SBATCH -e ${dir_err}/ptr.err.%j 
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J ${nickname}-${job}
# Queue (Partition):
#SBATCH --partition=${queue}
# Number of nodes and MPI tasks per node:
#SBATCH --nodes=${nodes}
#SBATCH --ntasks-per-node=${MPI_per_node}
# Enable Hyperthreading:
#SBATCH --ntasks-per-core=1

# for OpenMP:
#SBATCH --cpus-per-task=${CPUs_per_task}
#
#SBATCH --mail-type=none
#SBATCH --mail-user=${mail}
# Wall clock limit:
#SBATCH --time=${hour}:${min}:${second}

${misc}

cd ${dir_out}
cp ${prog} ${exe}

export OMP_NUM_THREADS=${OMP_NUM_THREADS}
export SRUN_CPUS_PER_TASK=$OMP_NUM_THREADS
# For pinning threads correctly:
export OMP_PLACES=cores

# Run the program:
srun ${exe} > ptr_${model}${info}_${job}.lst
rm ${exe}
